gotoLocations:
  lobby:
    world: world
    x: -61
    y: 66
    z: -807
  volcan:
    world: world
    x: 347
    y: 134
    z: -1407
  drapeau:
    world: world
    x: -5947
    y: 64
    z: -6473
  village:
    world: world
    x: 374
    y: 76
    z: -338
  chateau:
    world: world
    x: -4493
    y: 67
    z: -5451
  battleroyale1:
    world: world
    x: 438
    y: 64
    z: -1085
  bateau:
    world: world
    x: -163
    y: 255
    z: -720
  arbre:
    world: world
    x: -4
    y: 67
    z: -617
  battleroyalev3:
    world: world
    x: 1034
    y: 141
    z: -1185
  capturededrapeau:
    world: world
    x: -5947
    y: 64
    z: -6470
  grange:
    world: world
    x: 1369
    y: 76
    z: 1273
  course:
    world: world
    x: -161
    y: 255
    z: -721
  neige:
    world: world
    x: -4161
    y: 74
    z: -5633
maps:
  volcan:
    xPos: 231
    yPos: 97
    zPos: -1541
    height: 52
    side: 251
    spawnHeight: 150
    yOffsetBetweenMapAndModel: 66
    chestLocations:
    - - 253
      - 100
      - -1395
    - - 259
      - 107
      - -1412
    - - 272
      - 118
      - -1424
    - - 244
      - 116
      - -1412
    - - 244
      - 107
      - -1412
    - - 248
      - 102
      - -1430
    - - 248
      - 116
      - -1432
    - - 241
      - 107
      - -1453
    - - 232
      - 107
      - -1415
    - - 274
      - 107
      - -1340
    - - 254
      - 107
      - -1354
    - - 250
      - 107
      - -1378
    - - 294
      - 107
      - -1383
    - - 288
      - 107
      - -1357
    - - 314
      - 98
      - -1379
    - - 297
      - 98
      - -1399
    - - 296
      - 110
      - -1403
    - - 308
      - 107
      - -1427
    - - 296
      - 110
      - -1403
    - - 277
      - 107
      - -1424
    - - 326
      - 111
      - -1447
    - - 330
      - 121
      - -1431
    - - 274
      - 107
      - -1325
    - - 258
      - 107
      - -1483
    - - 290
      - 108
      - -1501
    - - 288
      - 107
      - -1510
    - - 286
      - 107
      - -1492
    - - 313
      - 108
      - -1516
    - - 345
      - 107
      - -1533
    - - 351
      - 109
      - -1512
    - - 347
      - 110
      - -1497
    - - 354
      - 110
      - -1514
    - - 359
      - 110
      - -1500
    - - 366
      - 109
      - -1505
    - - 377
      - 109
      - -1507
    - - 385
      - 111
      - -1501
    - - 389
      - 108
      - -1525
    - - 367
      - 107
      - -1538
    - - 364
      - 115
      - -1534
    - - 316
      - 118
      - -1490
    - - 352
      - 110
      - -1498
    - - 350
      - 128
      - -1501
    - - 405
      - 118
      - -1496
    - - 377
      - 118
      - -1458
    - - 340
      - 120
      - -1453
    - - 267
      - 107
      - -1402
    - - 239
      - 109
      - -1400
    - - 256
      - 111
      - -1439
    - - 269
      - 125
      - -1418
    - - 320
      - 114
      - -1399
    - - 326
      - 108
      - -1388
    - - 273
      - 114
      - -1372
    - - 274
      - 123
      - -1377
    - - 272
      - 136
      - -1379
    - - 264
      - 130
      - -1377
    - - 264
      - 133
      - -1385
    - - 262
      - 115
      - -1459
    - - 268
      - 115
      - -1468
    - - 291
      - 115
      - -1472
    - - 298
      - 115
      - -1440
    - - 273
      - 115
      - -1434
    - - 263
      - 115
      - -1444
    - - 276
      - 110
      - -1470
    - - 267
      - 110
      - -1465
    - - 296
      - 110
      - -1464
    - - 301
      - 110
      - -1450
    - - 285
      - 110
      - -1434
    - - 266
      - 110
      - -1444
    - - 356
      - 134
      - -1415
    - - 336
      - 134
      - -1416
    - - 345
      - 105
      - -1414
    - - 347
      - 108
      - -1415
    - - 347
      - 113
      - -1410
    - - 349
      - 121
      - -1418
    - - 348
      - 131
      - -1415
    - - 359
      - 117
      - -1400
    - - 346
      - 105
      - -1396
    - - 326
      - 104
      - -1424
    - - 383
      - 112
      - -1418
    - - 345
      - 122
      - -1396
    - - 361
      - 121
      - -1436
    - - 376
      - 119
      - -1424
    - - 382
      - 111
      - -1400
    - - 357
      - 107
      - -1377
    - - 369
      - 107
      - -1365
    - - 333
      - 111
      - -1375
    - - 299
      - 109
      - -1334
    - - 354
      - 128
      - -1432
    - - 371
      - 122
      - -1416
    - - 312
      - 111
      - -1356
    - - 345
      - 109
      - -1359
    - - 350
      - 109
      - -1370
    - - 363
      - 113
      - -1383
    - - 377
      - 112
      - -1376
    - - 393
      - 106
      - -1354
    - - 381
      - 110
      - -1325
    - - 402
      - 114
      - -1319
    - - 405
      - 121
      - -1317
    - - 350
      - 110
      - -1309
    - - 352
      - 122
      - -1307
    - - 336
      - 115
      - -1321
    - - 336
      - 115
      - -1314
    - - 329
      - 110
      - -1314
    - - 361
      - 114
      - -1330
    - - 354
      - 110
      - -1321
    - - 344
      - 123
      - -1302
    - - 378
      - 135
      - -1310
    - - 378
      - 135
      - -1311
    - - 380
      - 110
      - -1306
    - - 404
      - 109
      - -1317
    - - 404
      - 107
      - -1369
    - - 425
      - 108
      - -1375
    - - 418
      - 108
      - -1364
    - - 416
      - 109
      - -1347
    - - 425
      - 109
      - -1349
    - - 440
      - 108
      - -1349
    - - 447
      - 117
      - -1349
    - - 457
      - 111
      - -1359
    - - 444
      - 109
      - -1363
    - - 454
      - 108
      - -1367
    - - 460
      - 115
      - -1357
    - - 442
      - 116
      - -1360
    - - 458
      - 115
      - -1360
    - - 460
      - 107
      - -1349
    - - 443
      - 108
      - -1332
    - - 437
      - 109
      - -1382
    - - 434
      - 121
      - -1377
    - - 466
      - 106
      - -1389
    - - 468
      - 109
      - -1360
    - - 478
      - 107
      - -1400
    - - 462
      - 110
      - -1416
    - - 452
      - 107
      - -1419
    - - 435
      - 107
      - -1429
    - - 476
      - 107
      - -1436
    - - 464
      - 107
      - -1423
    - - 475
      - 108
      - -1445
    - - 479
      - 107
      - -1429
    - - 470
      - 111
      - -1428
    - - 466
      - 117
      - -1469
    - - 457
      - 117
      - -1489
    - - 419
      - 109
      - -1499
    - - 350
      - 109
      - -1472
    - - 268
      - 113
      - -1506
    - - 441
      - 113
      - -1507
    - - 410
      - 108
      - -1453
    - - 402
      - 107
      - -1423
    - - 393
      - 108
      - -1445
    - - 426
      - 115
      - -1462
  desertetjungle:
    xPos: 886
    yPos: 116
    zPos: -1316
    height: 84
    side: 238
    spawnHeight: 200
    yOffsetBetweenMapAndModel: 110
    chestLocations: